# Generated by Django 5.0.3 on 2024-04-08 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examcontroller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_no', models.CharField(blank=True, max_length=40, null=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examcontroller.semester')),
            ],
        ),
    ]
