# Generated by Django 5.0.3 on 2024-04-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examcontroller', '0004_rename_semesterno_subject_branchandsemester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examhall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallno', models.CharField(blank=True, max_length=20, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('columns', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='branchandsemester',
        ),
        migrations.AddField(
            model_name='subject',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
