# Generated by Django 5.0.3 on 2024-04-16 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examcontroller', '0005_examhall_remove_subject_branchandsemester_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='semesterno',
            new_name='semestername',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='branch',
        ),
        migrations.AlterField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examcontroller.branch'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examcontroller.semester'),
        ),
    ]
