# Generated by Django 5.0.3 on 2024-04-17 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examcontroller', '0006_rename_semesterno_semester_semestername_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='branchandsemester',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examcontroller.branch'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examcontroller.semester'),
        ),
    ]
