# Generated by Django 5.0.3 on 2024-04-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examcontroller', '0008_examdetails_created_at_examdetails_is_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Examhall',
            new_name='Classroom',
        ),
    ]
