# Generated by Django 5.0.3 on 2024-04-21 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examcontroller', '0009_rename_examhall_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seatingarrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.CharField(blank=True, max_length=100, null=True)),
                ('seat_number', models.CharField(blank=True, max_length=100, null=True)),
                ('classroom_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examcontroller.classroom')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examcontroller.semester')),
            ],
        ),
    ]
