# Generated by Django 5.0.3 on 2024-04-21 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examcontroller', '0010_seatingarrangement'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatingarrangement',
            name='register_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seatingarrangement',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examcontroller.subject'),
        ),
    ]
