# Generated by Django 5.0.3 on 2024-04-23 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examcontroller', '0012_teacherseatingarrangement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherseatingarrangement',
            name='exam_date',
        ),
        migrations.AddField(
            model_name='teacherseatingarrangement',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examcontroller.examdetails'),
        ),
    ]
