# Generated by Django 5.0.4 on 2024-04-28 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examcontroller', '0015_seatingarrangement_exam_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffsubject', to='examcontroller.subject'),
        ),
    ]
