# Generated by Django 5.0.3 on 2024-04-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EXAMCONTROLLER', 'Examcontroller'), ('STUDENT', 'Student'), ('STAFF', 'Staff')], max_length=20),
        ),
    ]
