# Generated by Django 5.0.4 on 2024-04-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('EXAMCONTROLLER', 'Examcontroller'), ('ADMIN', 'Admin'), ('STUDENT', 'Student')], max_length=20),
        ),
    ]
